---
- name: Python3 installation
  hosts: production
  gather_facts: false
  tasks:
    - name: Check for python3
      raw: test -e /usr/bin/python3
      changed_when: false
      failed_when: false
      register: check_python3
    - name: Install python3
      raw: yum -y install python3
      when: check_python3.rc != 0
